package pams.repository.dao;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import pams.repository.model.OdsbLargedepFlow;
import pams.repository.model.OdsbLargedepFlowExample;

import java.util.List;

@Component
public interface OdsbLargedepFlowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_LARGEDEP_FLOW
     *
     * @mbggenerated Sat Jan 26 23:08:57 CST 2013
     */
    int countByExample(OdsbLargedepFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_LARGEDEP_FLOW
     *
     * @mbggenerated Sat Jan 26 23:08:57 CST 2013
     */
    int deleteByExample(OdsbLargedepFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_LARGEDEP_FLOW
     *
     * @mbggenerated Sat Jan 26 23:08:57 CST 2013
     */
    int insert(OdsbLargedepFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_LARGEDEP_FLOW
     *
     * @mbggenerated Sat Jan 26 23:08:57 CST 2013
     */
    int insertSelective(OdsbLargedepFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_LARGEDEP_FLOW
     *
     * @mbggenerated Sat Jan 26 23:08:57 CST 2013
     */
    List<OdsbLargedepFlow> selectByExample(OdsbLargedepFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_LARGEDEP_FLOW
     *
     * @mbggenerated Sat Jan 26 23:08:57 CST 2013
     */
    int updateByExampleSelective(@Param("record") OdsbLargedepFlow record, @Param("example") OdsbLargedepFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_LARGEDEP_FLOW
     *
     * @mbggenerated Sat Jan 26 23:08:57 CST 2013
     */
    int updateByExample(@Param("record") OdsbLargedepFlow record, @Param("example") OdsbLargedepFlowExample example);
}