package pams.repository.model;

public class ClsRptdataKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLS_RPTDATA.BASE_CUSTNO_ECIF
     *
     * @mbggenerated Sun Dec 29 18:52:07 CST 2013
     */
    private String baseCustnoEcif;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLS_RPTDATA.RPT_DATE
     *
     * @mbggenerated Sun Dec 29 18:52:07 CST 2013
     */
    private String rptDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLS_RPTDATA.RPT_TYPE
     *
     * @mbggenerated Sun Dec 29 18:52:07 CST 2013
     */
    private String rptType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLS_RPTDATA.BASE_CUSTNO_ECIF
     *
     * @return the value of CLS_RPTDATA.BASE_CUSTNO_ECIF
     *
     * @mbggenerated Sun Dec 29 18:52:07 CST 2013
     */
    public String getBaseCustnoEcif() {
        return baseCustnoEcif;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLS_RPTDATA.BASE_CUSTNO_ECIF
     *
     * @param baseCustnoEcif the value for CLS_RPTDATA.BASE_CUSTNO_ECIF
     *
     * @mbggenerated Sun Dec 29 18:52:07 CST 2013
     */
    public void setBaseCustnoEcif(String baseCustnoEcif) {
        this.baseCustnoEcif = baseCustnoEcif == null ? null : baseCustnoEcif.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLS_RPTDATA.RPT_DATE
     *
     * @return the value of CLS_RPTDATA.RPT_DATE
     *
     * @mbggenerated Sun Dec 29 18:52:07 CST 2013
     */
    public String getRptDate() {
        return rptDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLS_RPTDATA.RPT_DATE
     *
     * @param rptDate the value for CLS_RPTDATA.RPT_DATE
     *
     * @mbggenerated Sun Dec 29 18:52:07 CST 2013
     */
    public void setRptDate(String rptDate) {
        this.rptDate = rptDate == null ? null : rptDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLS_RPTDATA.RPT_TYPE
     *
     * @return the value of CLS_RPTDATA.RPT_TYPE
     *
     * @mbggenerated Sun Dec 29 18:52:07 CST 2013
     */
    public String getRptType() {
        return rptType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLS_RPTDATA.RPT_TYPE
     *
     * @param rptType the value for CLS_RPTDATA.RPT_TYPE
     *
     * @mbggenerated Sun Dec 29 18:52:07 CST 2013
     */
    public void setRptType(String rptType) {
        this.rptType = rptType == null ? null : rptType.trim();
    }
}