package pams.repository.model;

import java.util.ArrayList;
import java.util.List;

public class ClsUdRptdataExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CLS_UD_RPTDATA
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CLS_UD_RPTDATA
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CLS_UD_RPTDATA
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_RPTDATA
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public ClsUdRptdataExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_RPTDATA
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_RPTDATA
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_RPTDATA
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_RPTDATA
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_RPTDATA
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_RPTDATA
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_RPTDATA
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_RPTDATA
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_RPTDATA
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_RPTDATA
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CLS_UD_RPTDATA
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGuidIsNull() {
            addCriterion("GUID is null");
            return (Criteria) this;
        }

        public Criteria andGuidIsNotNull() {
            addCriterion("GUID is not null");
            return (Criteria) this;
        }

        public Criteria andGuidEqualTo(String value) {
            addCriterion("GUID =", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotEqualTo(String value) {
            addCriterion("GUID <>", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidGreaterThan(String value) {
            addCriterion("GUID >", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidGreaterThanOrEqualTo(String value) {
            addCriterion("GUID >=", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidLessThan(String value) {
            addCriterion("GUID <", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidLessThanOrEqualTo(String value) {
            addCriterion("GUID <=", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidLike(String value) {
            addCriterion("GUID like", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotLike(String value) {
            addCriterion("GUID not like", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidIn(List<String> values) {
            addCriterion("GUID in", values, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotIn(List<String> values) {
            addCriterion("GUID not in", values, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidBetween(String value1, String value2) {
            addCriterion("GUID between", value1, value2, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotBetween(String value1, String value2) {
            addCriterion("GUID not between", value1, value2, "guid");
            return (Criteria) this;
        }

        public Criteria andRptdateIsNull() {
            addCriterion("RPTDATE is null");
            return (Criteria) this;
        }

        public Criteria andRptdateIsNotNull() {
            addCriterion("RPTDATE is not null");
            return (Criteria) this;
        }

        public Criteria andRptdateEqualTo(String value) {
            addCriterion("RPTDATE =", value, "rptdate");
            return (Criteria) this;
        }

        public Criteria andRptdateNotEqualTo(String value) {
            addCriterion("RPTDATE <>", value, "rptdate");
            return (Criteria) this;
        }

        public Criteria andRptdateGreaterThan(String value) {
            addCriterion("RPTDATE >", value, "rptdate");
            return (Criteria) this;
        }

        public Criteria andRptdateGreaterThanOrEqualTo(String value) {
            addCriterion("RPTDATE >=", value, "rptdate");
            return (Criteria) this;
        }

        public Criteria andRptdateLessThan(String value) {
            addCriterion("RPTDATE <", value, "rptdate");
            return (Criteria) this;
        }

        public Criteria andRptdateLessThanOrEqualTo(String value) {
            addCriterion("RPTDATE <=", value, "rptdate");
            return (Criteria) this;
        }

        public Criteria andRptdateLike(String value) {
            addCriterion("RPTDATE like", value, "rptdate");
            return (Criteria) this;
        }

        public Criteria andRptdateNotLike(String value) {
            addCriterion("RPTDATE not like", value, "rptdate");
            return (Criteria) this;
        }

        public Criteria andRptdateIn(List<String> values) {
            addCriterion("RPTDATE in", values, "rptdate");
            return (Criteria) this;
        }

        public Criteria andRptdateNotIn(List<String> values) {
            addCriterion("RPTDATE not in", values, "rptdate");
            return (Criteria) this;
        }

        public Criteria andRptdateBetween(String value1, String value2) {
            addCriterion("RPTDATE between", value1, value2, "rptdate");
            return (Criteria) this;
        }

        public Criteria andRptdateNotBetween(String value1, String value2) {
            addCriterion("RPTDATE not between", value1, value2, "rptdate");
            return (Criteria) this;
        }

        public Criteria andRptnoIsNull() {
            addCriterion("RPTNO is null");
            return (Criteria) this;
        }

        public Criteria andRptnoIsNotNull() {
            addCriterion("RPTNO is not null");
            return (Criteria) this;
        }

        public Criteria andRptnoEqualTo(String value) {
            addCriterion("RPTNO =", value, "rptno");
            return (Criteria) this;
        }

        public Criteria andRptnoNotEqualTo(String value) {
            addCriterion("RPTNO <>", value, "rptno");
            return (Criteria) this;
        }

        public Criteria andRptnoGreaterThan(String value) {
            addCriterion("RPTNO >", value, "rptno");
            return (Criteria) this;
        }

        public Criteria andRptnoGreaterThanOrEqualTo(String value) {
            addCriterion("RPTNO >=", value, "rptno");
            return (Criteria) this;
        }

        public Criteria andRptnoLessThan(String value) {
            addCriterion("RPTNO <", value, "rptno");
            return (Criteria) this;
        }

        public Criteria andRptnoLessThanOrEqualTo(String value) {
            addCriterion("RPTNO <=", value, "rptno");
            return (Criteria) this;
        }

        public Criteria andRptnoLike(String value) {
            addCriterion("RPTNO like", value, "rptno");
            return (Criteria) this;
        }

        public Criteria andRptnoNotLike(String value) {
            addCriterion("RPTNO not like", value, "rptno");
            return (Criteria) this;
        }

        public Criteria andRptnoIn(List<String> values) {
            addCriterion("RPTNO in", values, "rptno");
            return (Criteria) this;
        }

        public Criteria andRptnoNotIn(List<String> values) {
            addCriterion("RPTNO not in", values, "rptno");
            return (Criteria) this;
        }

        public Criteria andRptnoBetween(String value1, String value2) {
            addCriterion("RPTNO between", value1, value2, "rptno");
            return (Criteria) this;
        }

        public Criteria andRptnoNotBetween(String value1, String value2) {
            addCriterion("RPTNO not between", value1, value2, "rptno");
            return (Criteria) this;
        }

        public Criteria andBranchnameIsNull() {
            addCriterion("BRANCHNAME is null");
            return (Criteria) this;
        }

        public Criteria andBranchnameIsNotNull() {
            addCriterion("BRANCHNAME is not null");
            return (Criteria) this;
        }

        public Criteria andBranchnameEqualTo(String value) {
            addCriterion("BRANCHNAME =", value, "branchname");
            return (Criteria) this;
        }

        public Criteria andBranchnameNotEqualTo(String value) {
            addCriterion("BRANCHNAME <>", value, "branchname");
            return (Criteria) this;
        }

        public Criteria andBranchnameGreaterThan(String value) {
            addCriterion("BRANCHNAME >", value, "branchname");
            return (Criteria) this;
        }

        public Criteria andBranchnameGreaterThanOrEqualTo(String value) {
            addCriterion("BRANCHNAME >=", value, "branchname");
            return (Criteria) this;
        }

        public Criteria andBranchnameLessThan(String value) {
            addCriterion("BRANCHNAME <", value, "branchname");
            return (Criteria) this;
        }

        public Criteria andBranchnameLessThanOrEqualTo(String value) {
            addCriterion("BRANCHNAME <=", value, "branchname");
            return (Criteria) this;
        }

        public Criteria andBranchnameLike(String value) {
            addCriterion("BRANCHNAME like", value, "branchname");
            return (Criteria) this;
        }

        public Criteria andBranchnameNotLike(String value) {
            addCriterion("BRANCHNAME not like", value, "branchname");
            return (Criteria) this;
        }

        public Criteria andBranchnameIn(List<String> values) {
            addCriterion("BRANCHNAME in", values, "branchname");
            return (Criteria) this;
        }

        public Criteria andBranchnameNotIn(List<String> values) {
            addCriterion("BRANCHNAME not in", values, "branchname");
            return (Criteria) this;
        }

        public Criteria andBranchnameBetween(String value1, String value2) {
            addCriterion("BRANCHNAME between", value1, value2, "branchname");
            return (Criteria) this;
        }

        public Criteria andBranchnameNotBetween(String value1, String value2) {
            addCriterion("BRANCHNAME not between", value1, value2, "branchname");
            return (Criteria) this;
        }

        public Criteria andBranchidIsNull() {
            addCriterion("BRANCHID is null");
            return (Criteria) this;
        }

        public Criteria andBranchidIsNotNull() {
            addCriterion("BRANCHID is not null");
            return (Criteria) this;
        }

        public Criteria andBranchidEqualTo(String value) {
            addCriterion("BRANCHID =", value, "branchid");
            return (Criteria) this;
        }

        public Criteria andBranchidNotEqualTo(String value) {
            addCriterion("BRANCHID <>", value, "branchid");
            return (Criteria) this;
        }

        public Criteria andBranchidGreaterThan(String value) {
            addCriterion("BRANCHID >", value, "branchid");
            return (Criteria) this;
        }

        public Criteria andBranchidGreaterThanOrEqualTo(String value) {
            addCriterion("BRANCHID >=", value, "branchid");
            return (Criteria) this;
        }

        public Criteria andBranchidLessThan(String value) {
            addCriterion("BRANCHID <", value, "branchid");
            return (Criteria) this;
        }

        public Criteria andBranchidLessThanOrEqualTo(String value) {
            addCriterion("BRANCHID <=", value, "branchid");
            return (Criteria) this;
        }

        public Criteria andBranchidLike(String value) {
            addCriterion("BRANCHID like", value, "branchid");
            return (Criteria) this;
        }

        public Criteria andBranchidNotLike(String value) {
            addCriterion("BRANCHID not like", value, "branchid");
            return (Criteria) this;
        }

        public Criteria andBranchidIn(List<String> values) {
            addCriterion("BRANCHID in", values, "branchid");
            return (Criteria) this;
        }

        public Criteria andBranchidNotIn(List<String> values) {
            addCriterion("BRANCHID not in", values, "branchid");
            return (Criteria) this;
        }

        public Criteria andBranchidBetween(String value1, String value2) {
            addCriterion("BRANCHID between", value1, value2, "branchid");
            return (Criteria) this;
        }

        public Criteria andBranchidNotBetween(String value1, String value2) {
            addCriterion("BRANCHID not between", value1, value2, "branchid");
            return (Criteria) this;
        }

        public Criteria andCustnameIsNull() {
            addCriterion("CUSTNAME is null");
            return (Criteria) this;
        }

        public Criteria andCustnameIsNotNull() {
            addCriterion("CUSTNAME is not null");
            return (Criteria) this;
        }

        public Criteria andCustnameEqualTo(String value) {
            addCriterion("CUSTNAME =", value, "custname");
            return (Criteria) this;
        }

        public Criteria andCustnameNotEqualTo(String value) {
            addCriterion("CUSTNAME <>", value, "custname");
            return (Criteria) this;
        }

        public Criteria andCustnameGreaterThan(String value) {
            addCriterion("CUSTNAME >", value, "custname");
            return (Criteria) this;
        }

        public Criteria andCustnameGreaterThanOrEqualTo(String value) {
            addCriterion("CUSTNAME >=", value, "custname");
            return (Criteria) this;
        }

        public Criteria andCustnameLessThan(String value) {
            addCriterion("CUSTNAME <", value, "custname");
            return (Criteria) this;
        }

        public Criteria andCustnameLessThanOrEqualTo(String value) {
            addCriterion("CUSTNAME <=", value, "custname");
            return (Criteria) this;
        }

        public Criteria andCustnameLike(String value) {
            addCriterion("CUSTNAME like", value, "custname");
            return (Criteria) this;
        }

        public Criteria andCustnameNotLike(String value) {
            addCriterion("CUSTNAME not like", value, "custname");
            return (Criteria) this;
        }

        public Criteria andCustnameIn(List<String> values) {
            addCriterion("CUSTNAME in", values, "custname");
            return (Criteria) this;
        }

        public Criteria andCustnameNotIn(List<String> values) {
            addCriterion("CUSTNAME not in", values, "custname");
            return (Criteria) this;
        }

        public Criteria andCustnameBetween(String value1, String value2) {
            addCriterion("CUSTNAME between", value1, value2, "custname");
            return (Criteria) this;
        }

        public Criteria andCustnameNotBetween(String value1, String value2) {
            addCriterion("CUSTNAME not between", value1, value2, "custname");
            return (Criteria) this;
        }

        public Criteria andCustnoIsNull() {
            addCriterion("CUSTNO is null");
            return (Criteria) this;
        }

        public Criteria andCustnoIsNotNull() {
            addCriterion("CUSTNO is not null");
            return (Criteria) this;
        }

        public Criteria andCustnoEqualTo(String value) {
            addCriterion("CUSTNO =", value, "custno");
            return (Criteria) this;
        }

        public Criteria andCustnoNotEqualTo(String value) {
            addCriterion("CUSTNO <>", value, "custno");
            return (Criteria) this;
        }

        public Criteria andCustnoGreaterThan(String value) {
            addCriterion("CUSTNO >", value, "custno");
            return (Criteria) this;
        }

        public Criteria andCustnoGreaterThanOrEqualTo(String value) {
            addCriterion("CUSTNO >=", value, "custno");
            return (Criteria) this;
        }

        public Criteria andCustnoLessThan(String value) {
            addCriterion("CUSTNO <", value, "custno");
            return (Criteria) this;
        }

        public Criteria andCustnoLessThanOrEqualTo(String value) {
            addCriterion("CUSTNO <=", value, "custno");
            return (Criteria) this;
        }

        public Criteria andCustnoLike(String value) {
            addCriterion("CUSTNO like", value, "custno");
            return (Criteria) this;
        }

        public Criteria andCustnoNotLike(String value) {
            addCriterion("CUSTNO not like", value, "custno");
            return (Criteria) this;
        }

        public Criteria andCustnoIn(List<String> values) {
            addCriterion("CUSTNO in", values, "custno");
            return (Criteria) this;
        }

        public Criteria andCustnoNotIn(List<String> values) {
            addCriterion("CUSTNO not in", values, "custno");
            return (Criteria) this;
        }

        public Criteria andCustnoBetween(String value1, String value2) {
            addCriterion("CUSTNO between", value1, value2, "custno");
            return (Criteria) this;
        }

        public Criteria andCustnoNotBetween(String value1, String value2) {
            addCriterion("CUSTNO not between", value1, value2, "custno");
            return (Criteria) this;
        }

        public Criteria andCustphone1IsNull() {
            addCriterion("CUSTPHONE1 is null");
            return (Criteria) this;
        }

        public Criteria andCustphone1IsNotNull() {
            addCriterion("CUSTPHONE1 is not null");
            return (Criteria) this;
        }

        public Criteria andCustphone1EqualTo(String value) {
            addCriterion("CUSTPHONE1 =", value, "custphone1");
            return (Criteria) this;
        }

        public Criteria andCustphone1NotEqualTo(String value) {
            addCriterion("CUSTPHONE1 <>", value, "custphone1");
            return (Criteria) this;
        }

        public Criteria andCustphone1GreaterThan(String value) {
            addCriterion("CUSTPHONE1 >", value, "custphone1");
            return (Criteria) this;
        }

        public Criteria andCustphone1GreaterThanOrEqualTo(String value) {
            addCriterion("CUSTPHONE1 >=", value, "custphone1");
            return (Criteria) this;
        }

        public Criteria andCustphone1LessThan(String value) {
            addCriterion("CUSTPHONE1 <", value, "custphone1");
            return (Criteria) this;
        }

        public Criteria andCustphone1LessThanOrEqualTo(String value) {
            addCriterion("CUSTPHONE1 <=", value, "custphone1");
            return (Criteria) this;
        }

        public Criteria andCustphone1Like(String value) {
            addCriterion("CUSTPHONE1 like", value, "custphone1");
            return (Criteria) this;
        }

        public Criteria andCustphone1NotLike(String value) {
            addCriterion("CUSTPHONE1 not like", value, "custphone1");
            return (Criteria) this;
        }

        public Criteria andCustphone1In(List<String> values) {
            addCriterion("CUSTPHONE1 in", values, "custphone1");
            return (Criteria) this;
        }

        public Criteria andCustphone1NotIn(List<String> values) {
            addCriterion("CUSTPHONE1 not in", values, "custphone1");
            return (Criteria) this;
        }

        public Criteria andCustphone1Between(String value1, String value2) {
            addCriterion("CUSTPHONE1 between", value1, value2, "custphone1");
            return (Criteria) this;
        }

        public Criteria andCustphone1NotBetween(String value1, String value2) {
            addCriterion("CUSTPHONE1 not between", value1, value2, "custphone1");
            return (Criteria) this;
        }

        public Criteria andAumIsNull() {
            addCriterion("AUM is null");
            return (Criteria) this;
        }

        public Criteria andAumIsNotNull() {
            addCriterion("AUM is not null");
            return (Criteria) this;
        }

        public Criteria andAumEqualTo(String value) {
            addCriterion("AUM =", value, "aum");
            return (Criteria) this;
        }

        public Criteria andAumNotEqualTo(String value) {
            addCriterion("AUM <>", value, "aum");
            return (Criteria) this;
        }

        public Criteria andAumGreaterThan(String value) {
            addCriterion("AUM >", value, "aum");
            return (Criteria) this;
        }

        public Criteria andAumGreaterThanOrEqualTo(String value) {
            addCriterion("AUM >=", value, "aum");
            return (Criteria) this;
        }

        public Criteria andAumLessThan(String value) {
            addCriterion("AUM <", value, "aum");
            return (Criteria) this;
        }

        public Criteria andAumLessThanOrEqualTo(String value) {
            addCriterion("AUM <=", value, "aum");
            return (Criteria) this;
        }

        public Criteria andAumLike(String value) {
            addCriterion("AUM like", value, "aum");
            return (Criteria) this;
        }

        public Criteria andAumNotLike(String value) {
            addCriterion("AUM not like", value, "aum");
            return (Criteria) this;
        }

        public Criteria andAumIn(List<String> values) {
            addCriterion("AUM in", values, "aum");
            return (Criteria) this;
        }

        public Criteria andAumNotIn(List<String> values) {
            addCriterion("AUM not in", values, "aum");
            return (Criteria) this;
        }

        public Criteria andAumBetween(String value1, String value2) {
            addCriterion("AUM between", value1, value2, "aum");
            return (Criteria) this;
        }

        public Criteria andAumNotBetween(String value1, String value2) {
            addCriterion("AUM not between", value1, value2, "aum");
            return (Criteria) this;
        }

        public Criteria andBalIsNull() {
            addCriterion("BAL is null");
            return (Criteria) this;
        }

        public Criteria andBalIsNotNull() {
            addCriterion("BAL is not null");
            return (Criteria) this;
        }

        public Criteria andBalEqualTo(String value) {
            addCriterion("BAL =", value, "bal");
            return (Criteria) this;
        }

        public Criteria andBalNotEqualTo(String value) {
            addCriterion("BAL <>", value, "bal");
            return (Criteria) this;
        }

        public Criteria andBalGreaterThan(String value) {
            addCriterion("BAL >", value, "bal");
            return (Criteria) this;
        }

        public Criteria andBalGreaterThanOrEqualTo(String value) {
            addCriterion("BAL >=", value, "bal");
            return (Criteria) this;
        }

        public Criteria andBalLessThan(String value) {
            addCriterion("BAL <", value, "bal");
            return (Criteria) this;
        }

        public Criteria andBalLessThanOrEqualTo(String value) {
            addCriterion("BAL <=", value, "bal");
            return (Criteria) this;
        }

        public Criteria andBalLike(String value) {
            addCriterion("BAL like", value, "bal");
            return (Criteria) this;
        }

        public Criteria andBalNotLike(String value) {
            addCriterion("BAL not like", value, "bal");
            return (Criteria) this;
        }

        public Criteria andBalIn(List<String> values) {
            addCriterion("BAL in", values, "bal");
            return (Criteria) this;
        }

        public Criteria andBalNotIn(List<String> values) {
            addCriterion("BAL not in", values, "bal");
            return (Criteria) this;
        }

        public Criteria andBalBetween(String value1, String value2) {
            addCriterion("BAL between", value1, value2, "bal");
            return (Criteria) this;
        }

        public Criteria andBalNotBetween(String value1, String value2) {
            addCriterion("BAL not between", value1, value2, "bal");
            return (Criteria) this;
        }

        public Criteria andFld01IsNull() {
            addCriterion("FLD01 is null");
            return (Criteria) this;
        }

        public Criteria andFld01IsNotNull() {
            addCriterion("FLD01 is not null");
            return (Criteria) this;
        }

        public Criteria andFld01EqualTo(String value) {
            addCriterion("FLD01 =", value, "fld01");
            return (Criteria) this;
        }

        public Criteria andFld01NotEqualTo(String value) {
            addCriterion("FLD01 <>", value, "fld01");
            return (Criteria) this;
        }

        public Criteria andFld01GreaterThan(String value) {
            addCriterion("FLD01 >", value, "fld01");
            return (Criteria) this;
        }

        public Criteria andFld01GreaterThanOrEqualTo(String value) {
            addCriterion("FLD01 >=", value, "fld01");
            return (Criteria) this;
        }

        public Criteria andFld01LessThan(String value) {
            addCriterion("FLD01 <", value, "fld01");
            return (Criteria) this;
        }

        public Criteria andFld01LessThanOrEqualTo(String value) {
            addCriterion("FLD01 <=", value, "fld01");
            return (Criteria) this;
        }

        public Criteria andFld01Like(String value) {
            addCriterion("FLD01 like", value, "fld01");
            return (Criteria) this;
        }

        public Criteria andFld01NotLike(String value) {
            addCriterion("FLD01 not like", value, "fld01");
            return (Criteria) this;
        }

        public Criteria andFld01In(List<String> values) {
            addCriterion("FLD01 in", values, "fld01");
            return (Criteria) this;
        }

        public Criteria andFld01NotIn(List<String> values) {
            addCriterion("FLD01 not in", values, "fld01");
            return (Criteria) this;
        }

        public Criteria andFld01Between(String value1, String value2) {
            addCriterion("FLD01 between", value1, value2, "fld01");
            return (Criteria) this;
        }

        public Criteria andFld01NotBetween(String value1, String value2) {
            addCriterion("FLD01 not between", value1, value2, "fld01");
            return (Criteria) this;
        }

        public Criteria andFld02IsNull() {
            addCriterion("FLD02 is null");
            return (Criteria) this;
        }

        public Criteria andFld02IsNotNull() {
            addCriterion("FLD02 is not null");
            return (Criteria) this;
        }

        public Criteria andFld02EqualTo(String value) {
            addCriterion("FLD02 =", value, "fld02");
            return (Criteria) this;
        }

        public Criteria andFld02NotEqualTo(String value) {
            addCriterion("FLD02 <>", value, "fld02");
            return (Criteria) this;
        }

        public Criteria andFld02GreaterThan(String value) {
            addCriterion("FLD02 >", value, "fld02");
            return (Criteria) this;
        }

        public Criteria andFld02GreaterThanOrEqualTo(String value) {
            addCriterion("FLD02 >=", value, "fld02");
            return (Criteria) this;
        }

        public Criteria andFld02LessThan(String value) {
            addCriterion("FLD02 <", value, "fld02");
            return (Criteria) this;
        }

        public Criteria andFld02LessThanOrEqualTo(String value) {
            addCriterion("FLD02 <=", value, "fld02");
            return (Criteria) this;
        }

        public Criteria andFld02Like(String value) {
            addCriterion("FLD02 like", value, "fld02");
            return (Criteria) this;
        }

        public Criteria andFld02NotLike(String value) {
            addCriterion("FLD02 not like", value, "fld02");
            return (Criteria) this;
        }

        public Criteria andFld02In(List<String> values) {
            addCriterion("FLD02 in", values, "fld02");
            return (Criteria) this;
        }

        public Criteria andFld02NotIn(List<String> values) {
            addCriterion("FLD02 not in", values, "fld02");
            return (Criteria) this;
        }

        public Criteria andFld02Between(String value1, String value2) {
            addCriterion("FLD02 between", value1, value2, "fld02");
            return (Criteria) this;
        }

        public Criteria andFld02NotBetween(String value1, String value2) {
            addCriterion("FLD02 not between", value1, value2, "fld02");
            return (Criteria) this;
        }

        public Criteria andFld03IsNull() {
            addCriterion("FLD03 is null");
            return (Criteria) this;
        }

        public Criteria andFld03IsNotNull() {
            addCriterion("FLD03 is not null");
            return (Criteria) this;
        }

        public Criteria andFld03EqualTo(String value) {
            addCriterion("FLD03 =", value, "fld03");
            return (Criteria) this;
        }

        public Criteria andFld03NotEqualTo(String value) {
            addCriterion("FLD03 <>", value, "fld03");
            return (Criteria) this;
        }

        public Criteria andFld03GreaterThan(String value) {
            addCriterion("FLD03 >", value, "fld03");
            return (Criteria) this;
        }

        public Criteria andFld03GreaterThanOrEqualTo(String value) {
            addCriterion("FLD03 >=", value, "fld03");
            return (Criteria) this;
        }

        public Criteria andFld03LessThan(String value) {
            addCriterion("FLD03 <", value, "fld03");
            return (Criteria) this;
        }

        public Criteria andFld03LessThanOrEqualTo(String value) {
            addCriterion("FLD03 <=", value, "fld03");
            return (Criteria) this;
        }

        public Criteria andFld03Like(String value) {
            addCriterion("FLD03 like", value, "fld03");
            return (Criteria) this;
        }

        public Criteria andFld03NotLike(String value) {
            addCriterion("FLD03 not like", value, "fld03");
            return (Criteria) this;
        }

        public Criteria andFld03In(List<String> values) {
            addCriterion("FLD03 in", values, "fld03");
            return (Criteria) this;
        }

        public Criteria andFld03NotIn(List<String> values) {
            addCriterion("FLD03 not in", values, "fld03");
            return (Criteria) this;
        }

        public Criteria andFld03Between(String value1, String value2) {
            addCriterion("FLD03 between", value1, value2, "fld03");
            return (Criteria) this;
        }

        public Criteria andFld03NotBetween(String value1, String value2) {
            addCriterion("FLD03 not between", value1, value2, "fld03");
            return (Criteria) this;
        }

        public Criteria andFld04IsNull() {
            addCriterion("FLD04 is null");
            return (Criteria) this;
        }

        public Criteria andFld04IsNotNull() {
            addCriterion("FLD04 is not null");
            return (Criteria) this;
        }

        public Criteria andFld04EqualTo(String value) {
            addCriterion("FLD04 =", value, "fld04");
            return (Criteria) this;
        }

        public Criteria andFld04NotEqualTo(String value) {
            addCriterion("FLD04 <>", value, "fld04");
            return (Criteria) this;
        }

        public Criteria andFld04GreaterThan(String value) {
            addCriterion("FLD04 >", value, "fld04");
            return (Criteria) this;
        }

        public Criteria andFld04GreaterThanOrEqualTo(String value) {
            addCriterion("FLD04 >=", value, "fld04");
            return (Criteria) this;
        }

        public Criteria andFld04LessThan(String value) {
            addCriterion("FLD04 <", value, "fld04");
            return (Criteria) this;
        }

        public Criteria andFld04LessThanOrEqualTo(String value) {
            addCriterion("FLD04 <=", value, "fld04");
            return (Criteria) this;
        }

        public Criteria andFld04Like(String value) {
            addCriterion("FLD04 like", value, "fld04");
            return (Criteria) this;
        }

        public Criteria andFld04NotLike(String value) {
            addCriterion("FLD04 not like", value, "fld04");
            return (Criteria) this;
        }

        public Criteria andFld04In(List<String> values) {
            addCriterion("FLD04 in", values, "fld04");
            return (Criteria) this;
        }

        public Criteria andFld04NotIn(List<String> values) {
            addCriterion("FLD04 not in", values, "fld04");
            return (Criteria) this;
        }

        public Criteria andFld04Between(String value1, String value2) {
            addCriterion("FLD04 between", value1, value2, "fld04");
            return (Criteria) this;
        }

        public Criteria andFld04NotBetween(String value1, String value2) {
            addCriterion("FLD04 not between", value1, value2, "fld04");
            return (Criteria) this;
        }

        public Criteria andFld05IsNull() {
            addCriterion("FLD05 is null");
            return (Criteria) this;
        }

        public Criteria andFld05IsNotNull() {
            addCriterion("FLD05 is not null");
            return (Criteria) this;
        }

        public Criteria andFld05EqualTo(String value) {
            addCriterion("FLD05 =", value, "fld05");
            return (Criteria) this;
        }

        public Criteria andFld05NotEqualTo(String value) {
            addCriterion("FLD05 <>", value, "fld05");
            return (Criteria) this;
        }

        public Criteria andFld05GreaterThan(String value) {
            addCriterion("FLD05 >", value, "fld05");
            return (Criteria) this;
        }

        public Criteria andFld05GreaterThanOrEqualTo(String value) {
            addCriterion("FLD05 >=", value, "fld05");
            return (Criteria) this;
        }

        public Criteria andFld05LessThan(String value) {
            addCriterion("FLD05 <", value, "fld05");
            return (Criteria) this;
        }

        public Criteria andFld05LessThanOrEqualTo(String value) {
            addCriterion("FLD05 <=", value, "fld05");
            return (Criteria) this;
        }

        public Criteria andFld05Like(String value) {
            addCriterion("FLD05 like", value, "fld05");
            return (Criteria) this;
        }

        public Criteria andFld05NotLike(String value) {
            addCriterion("FLD05 not like", value, "fld05");
            return (Criteria) this;
        }

        public Criteria andFld05In(List<String> values) {
            addCriterion("FLD05 in", values, "fld05");
            return (Criteria) this;
        }

        public Criteria andFld05NotIn(List<String> values) {
            addCriterion("FLD05 not in", values, "fld05");
            return (Criteria) this;
        }

        public Criteria andFld05Between(String value1, String value2) {
            addCriterion("FLD05 between", value1, value2, "fld05");
            return (Criteria) this;
        }

        public Criteria andFld05NotBetween(String value1, String value2) {
            addCriterion("FLD05 not between", value1, value2, "fld05");
            return (Criteria) this;
        }

        public Criteria andFld06IsNull() {
            addCriterion("FLD06 is null");
            return (Criteria) this;
        }

        public Criteria andFld06IsNotNull() {
            addCriterion("FLD06 is not null");
            return (Criteria) this;
        }

        public Criteria andFld06EqualTo(String value) {
            addCriterion("FLD06 =", value, "fld06");
            return (Criteria) this;
        }

        public Criteria andFld06NotEqualTo(String value) {
            addCriterion("FLD06 <>", value, "fld06");
            return (Criteria) this;
        }

        public Criteria andFld06GreaterThan(String value) {
            addCriterion("FLD06 >", value, "fld06");
            return (Criteria) this;
        }

        public Criteria andFld06GreaterThanOrEqualTo(String value) {
            addCriterion("FLD06 >=", value, "fld06");
            return (Criteria) this;
        }

        public Criteria andFld06LessThan(String value) {
            addCriterion("FLD06 <", value, "fld06");
            return (Criteria) this;
        }

        public Criteria andFld06LessThanOrEqualTo(String value) {
            addCriterion("FLD06 <=", value, "fld06");
            return (Criteria) this;
        }

        public Criteria andFld06Like(String value) {
            addCriterion("FLD06 like", value, "fld06");
            return (Criteria) this;
        }

        public Criteria andFld06NotLike(String value) {
            addCriterion("FLD06 not like", value, "fld06");
            return (Criteria) this;
        }

        public Criteria andFld06In(List<String> values) {
            addCriterion("FLD06 in", values, "fld06");
            return (Criteria) this;
        }

        public Criteria andFld06NotIn(List<String> values) {
            addCriterion("FLD06 not in", values, "fld06");
            return (Criteria) this;
        }

        public Criteria andFld06Between(String value1, String value2) {
            addCriterion("FLD06 between", value1, value2, "fld06");
            return (Criteria) this;
        }

        public Criteria andFld06NotBetween(String value1, String value2) {
            addCriterion("FLD06 not between", value1, value2, "fld06");
            return (Criteria) this;
        }

        public Criteria andFld07IsNull() {
            addCriterion("FLD07 is null");
            return (Criteria) this;
        }

        public Criteria andFld07IsNotNull() {
            addCriterion("FLD07 is not null");
            return (Criteria) this;
        }

        public Criteria andFld07EqualTo(String value) {
            addCriterion("FLD07 =", value, "fld07");
            return (Criteria) this;
        }

        public Criteria andFld07NotEqualTo(String value) {
            addCriterion("FLD07 <>", value, "fld07");
            return (Criteria) this;
        }

        public Criteria andFld07GreaterThan(String value) {
            addCriterion("FLD07 >", value, "fld07");
            return (Criteria) this;
        }

        public Criteria andFld07GreaterThanOrEqualTo(String value) {
            addCriterion("FLD07 >=", value, "fld07");
            return (Criteria) this;
        }

        public Criteria andFld07LessThan(String value) {
            addCriterion("FLD07 <", value, "fld07");
            return (Criteria) this;
        }

        public Criteria andFld07LessThanOrEqualTo(String value) {
            addCriterion("FLD07 <=", value, "fld07");
            return (Criteria) this;
        }

        public Criteria andFld07Like(String value) {
            addCriterion("FLD07 like", value, "fld07");
            return (Criteria) this;
        }

        public Criteria andFld07NotLike(String value) {
            addCriterion("FLD07 not like", value, "fld07");
            return (Criteria) this;
        }

        public Criteria andFld07In(List<String> values) {
            addCriterion("FLD07 in", values, "fld07");
            return (Criteria) this;
        }

        public Criteria andFld07NotIn(List<String> values) {
            addCriterion("FLD07 not in", values, "fld07");
            return (Criteria) this;
        }

        public Criteria andFld07Between(String value1, String value2) {
            addCriterion("FLD07 between", value1, value2, "fld07");
            return (Criteria) this;
        }

        public Criteria andFld07NotBetween(String value1, String value2) {
            addCriterion("FLD07 not between", value1, value2, "fld07");
            return (Criteria) this;
        }

        public Criteria andFld08IsNull() {
            addCriterion("FLD08 is null");
            return (Criteria) this;
        }

        public Criteria andFld08IsNotNull() {
            addCriterion("FLD08 is not null");
            return (Criteria) this;
        }

        public Criteria andFld08EqualTo(String value) {
            addCriterion("FLD08 =", value, "fld08");
            return (Criteria) this;
        }

        public Criteria andFld08NotEqualTo(String value) {
            addCriterion("FLD08 <>", value, "fld08");
            return (Criteria) this;
        }

        public Criteria andFld08GreaterThan(String value) {
            addCriterion("FLD08 >", value, "fld08");
            return (Criteria) this;
        }

        public Criteria andFld08GreaterThanOrEqualTo(String value) {
            addCriterion("FLD08 >=", value, "fld08");
            return (Criteria) this;
        }

        public Criteria andFld08LessThan(String value) {
            addCriterion("FLD08 <", value, "fld08");
            return (Criteria) this;
        }

        public Criteria andFld08LessThanOrEqualTo(String value) {
            addCriterion("FLD08 <=", value, "fld08");
            return (Criteria) this;
        }

        public Criteria andFld08Like(String value) {
            addCriterion("FLD08 like", value, "fld08");
            return (Criteria) this;
        }

        public Criteria andFld08NotLike(String value) {
            addCriterion("FLD08 not like", value, "fld08");
            return (Criteria) this;
        }

        public Criteria andFld08In(List<String> values) {
            addCriterion("FLD08 in", values, "fld08");
            return (Criteria) this;
        }

        public Criteria andFld08NotIn(List<String> values) {
            addCriterion("FLD08 not in", values, "fld08");
            return (Criteria) this;
        }

        public Criteria andFld08Between(String value1, String value2) {
            addCriterion("FLD08 between", value1, value2, "fld08");
            return (Criteria) this;
        }

        public Criteria andFld08NotBetween(String value1, String value2) {
            addCriterion("FLD08 not between", value1, value2, "fld08");
            return (Criteria) this;
        }

        public Criteria andFld09IsNull() {
            addCriterion("FLD09 is null");
            return (Criteria) this;
        }

        public Criteria andFld09IsNotNull() {
            addCriterion("FLD09 is not null");
            return (Criteria) this;
        }

        public Criteria andFld09EqualTo(String value) {
            addCriterion("FLD09 =", value, "fld09");
            return (Criteria) this;
        }

        public Criteria andFld09NotEqualTo(String value) {
            addCriterion("FLD09 <>", value, "fld09");
            return (Criteria) this;
        }

        public Criteria andFld09GreaterThan(String value) {
            addCriterion("FLD09 >", value, "fld09");
            return (Criteria) this;
        }

        public Criteria andFld09GreaterThanOrEqualTo(String value) {
            addCriterion("FLD09 >=", value, "fld09");
            return (Criteria) this;
        }

        public Criteria andFld09LessThan(String value) {
            addCriterion("FLD09 <", value, "fld09");
            return (Criteria) this;
        }

        public Criteria andFld09LessThanOrEqualTo(String value) {
            addCriterion("FLD09 <=", value, "fld09");
            return (Criteria) this;
        }

        public Criteria andFld09Like(String value) {
            addCriterion("FLD09 like", value, "fld09");
            return (Criteria) this;
        }

        public Criteria andFld09NotLike(String value) {
            addCriterion("FLD09 not like", value, "fld09");
            return (Criteria) this;
        }

        public Criteria andFld09In(List<String> values) {
            addCriterion("FLD09 in", values, "fld09");
            return (Criteria) this;
        }

        public Criteria andFld09NotIn(List<String> values) {
            addCriterion("FLD09 not in", values, "fld09");
            return (Criteria) this;
        }

        public Criteria andFld09Between(String value1, String value2) {
            addCriterion("FLD09 between", value1, value2, "fld09");
            return (Criteria) this;
        }

        public Criteria andFld09NotBetween(String value1, String value2) {
            addCriterion("FLD09 not between", value1, value2, "fld09");
            return (Criteria) this;
        }

        public Criteria andFld10IsNull() {
            addCriterion("FLD10 is null");
            return (Criteria) this;
        }

        public Criteria andFld10IsNotNull() {
            addCriterion("FLD10 is not null");
            return (Criteria) this;
        }

        public Criteria andFld10EqualTo(String value) {
            addCriterion("FLD10 =", value, "fld10");
            return (Criteria) this;
        }

        public Criteria andFld10NotEqualTo(String value) {
            addCriterion("FLD10 <>", value, "fld10");
            return (Criteria) this;
        }

        public Criteria andFld10GreaterThan(String value) {
            addCriterion("FLD10 >", value, "fld10");
            return (Criteria) this;
        }

        public Criteria andFld10GreaterThanOrEqualTo(String value) {
            addCriterion("FLD10 >=", value, "fld10");
            return (Criteria) this;
        }

        public Criteria andFld10LessThan(String value) {
            addCriterion("FLD10 <", value, "fld10");
            return (Criteria) this;
        }

        public Criteria andFld10LessThanOrEqualTo(String value) {
            addCriterion("FLD10 <=", value, "fld10");
            return (Criteria) this;
        }

        public Criteria andFld10Like(String value) {
            addCriterion("FLD10 like", value, "fld10");
            return (Criteria) this;
        }

        public Criteria andFld10NotLike(String value) {
            addCriterion("FLD10 not like", value, "fld10");
            return (Criteria) this;
        }

        public Criteria andFld10In(List<String> values) {
            addCriterion("FLD10 in", values, "fld10");
            return (Criteria) this;
        }

        public Criteria andFld10NotIn(List<String> values) {
            addCriterion("FLD10 not in", values, "fld10");
            return (Criteria) this;
        }

        public Criteria andFld10Between(String value1, String value2) {
            addCriterion("FLD10 between", value1, value2, "fld10");
            return (Criteria) this;
        }

        public Criteria andFld10NotBetween(String value1, String value2) {
            addCriterion("FLD10 not between", value1, value2, "fld10");
            return (Criteria) this;
        }

        public Criteria andFld11IsNull() {
            addCriterion("FLD11 is null");
            return (Criteria) this;
        }

        public Criteria andFld11IsNotNull() {
            addCriterion("FLD11 is not null");
            return (Criteria) this;
        }

        public Criteria andFld11EqualTo(String value) {
            addCriterion("FLD11 =", value, "fld11");
            return (Criteria) this;
        }

        public Criteria andFld11NotEqualTo(String value) {
            addCriterion("FLD11 <>", value, "fld11");
            return (Criteria) this;
        }

        public Criteria andFld11GreaterThan(String value) {
            addCriterion("FLD11 >", value, "fld11");
            return (Criteria) this;
        }

        public Criteria andFld11GreaterThanOrEqualTo(String value) {
            addCriterion("FLD11 >=", value, "fld11");
            return (Criteria) this;
        }

        public Criteria andFld11LessThan(String value) {
            addCriterion("FLD11 <", value, "fld11");
            return (Criteria) this;
        }

        public Criteria andFld11LessThanOrEqualTo(String value) {
            addCriterion("FLD11 <=", value, "fld11");
            return (Criteria) this;
        }

        public Criteria andFld11Like(String value) {
            addCriterion("FLD11 like", value, "fld11");
            return (Criteria) this;
        }

        public Criteria andFld11NotLike(String value) {
            addCriterion("FLD11 not like", value, "fld11");
            return (Criteria) this;
        }

        public Criteria andFld11In(List<String> values) {
            addCriterion("FLD11 in", values, "fld11");
            return (Criteria) this;
        }

        public Criteria andFld11NotIn(List<String> values) {
            addCriterion("FLD11 not in", values, "fld11");
            return (Criteria) this;
        }

        public Criteria andFld11Between(String value1, String value2) {
            addCriterion("FLD11 between", value1, value2, "fld11");
            return (Criteria) this;
        }

        public Criteria andFld11NotBetween(String value1, String value2) {
            addCriterion("FLD11 not between", value1, value2, "fld11");
            return (Criteria) this;
        }

        public Criteria andFld12IsNull() {
            addCriterion("FLD12 is null");
            return (Criteria) this;
        }

        public Criteria andFld12IsNotNull() {
            addCriterion("FLD12 is not null");
            return (Criteria) this;
        }

        public Criteria andFld12EqualTo(String value) {
            addCriterion("FLD12 =", value, "fld12");
            return (Criteria) this;
        }

        public Criteria andFld12NotEqualTo(String value) {
            addCriterion("FLD12 <>", value, "fld12");
            return (Criteria) this;
        }

        public Criteria andFld12GreaterThan(String value) {
            addCriterion("FLD12 >", value, "fld12");
            return (Criteria) this;
        }

        public Criteria andFld12GreaterThanOrEqualTo(String value) {
            addCriterion("FLD12 >=", value, "fld12");
            return (Criteria) this;
        }

        public Criteria andFld12LessThan(String value) {
            addCriterion("FLD12 <", value, "fld12");
            return (Criteria) this;
        }

        public Criteria andFld12LessThanOrEqualTo(String value) {
            addCriterion("FLD12 <=", value, "fld12");
            return (Criteria) this;
        }

        public Criteria andFld12Like(String value) {
            addCriterion("FLD12 like", value, "fld12");
            return (Criteria) this;
        }

        public Criteria andFld12NotLike(String value) {
            addCriterion("FLD12 not like", value, "fld12");
            return (Criteria) this;
        }

        public Criteria andFld12In(List<String> values) {
            addCriterion("FLD12 in", values, "fld12");
            return (Criteria) this;
        }

        public Criteria andFld12NotIn(List<String> values) {
            addCriterion("FLD12 not in", values, "fld12");
            return (Criteria) this;
        }

        public Criteria andFld12Between(String value1, String value2) {
            addCriterion("FLD12 between", value1, value2, "fld12");
            return (Criteria) this;
        }

        public Criteria andFld12NotBetween(String value1, String value2) {
            addCriterion("FLD12 not between", value1, value2, "fld12");
            return (Criteria) this;
        }

        public Criteria andFld13IsNull() {
            addCriterion("FLD13 is null");
            return (Criteria) this;
        }

        public Criteria andFld13IsNotNull() {
            addCriterion("FLD13 is not null");
            return (Criteria) this;
        }

        public Criteria andFld13EqualTo(String value) {
            addCriterion("FLD13 =", value, "fld13");
            return (Criteria) this;
        }

        public Criteria andFld13NotEqualTo(String value) {
            addCriterion("FLD13 <>", value, "fld13");
            return (Criteria) this;
        }

        public Criteria andFld13GreaterThan(String value) {
            addCriterion("FLD13 >", value, "fld13");
            return (Criteria) this;
        }

        public Criteria andFld13GreaterThanOrEqualTo(String value) {
            addCriterion("FLD13 >=", value, "fld13");
            return (Criteria) this;
        }

        public Criteria andFld13LessThan(String value) {
            addCriterion("FLD13 <", value, "fld13");
            return (Criteria) this;
        }

        public Criteria andFld13LessThanOrEqualTo(String value) {
            addCriterion("FLD13 <=", value, "fld13");
            return (Criteria) this;
        }

        public Criteria andFld13Like(String value) {
            addCriterion("FLD13 like", value, "fld13");
            return (Criteria) this;
        }

        public Criteria andFld13NotLike(String value) {
            addCriterion("FLD13 not like", value, "fld13");
            return (Criteria) this;
        }

        public Criteria andFld13In(List<String> values) {
            addCriterion("FLD13 in", values, "fld13");
            return (Criteria) this;
        }

        public Criteria andFld13NotIn(List<String> values) {
            addCriterion("FLD13 not in", values, "fld13");
            return (Criteria) this;
        }

        public Criteria andFld13Between(String value1, String value2) {
            addCriterion("FLD13 between", value1, value2, "fld13");
            return (Criteria) this;
        }

        public Criteria andFld13NotBetween(String value1, String value2) {
            addCriterion("FLD13 not between", value1, value2, "fld13");
            return (Criteria) this;
        }

        public Criteria andFld14IsNull() {
            addCriterion("FLD14 is null");
            return (Criteria) this;
        }

        public Criteria andFld14IsNotNull() {
            addCriterion("FLD14 is not null");
            return (Criteria) this;
        }

        public Criteria andFld14EqualTo(String value) {
            addCriterion("FLD14 =", value, "fld14");
            return (Criteria) this;
        }

        public Criteria andFld14NotEqualTo(String value) {
            addCriterion("FLD14 <>", value, "fld14");
            return (Criteria) this;
        }

        public Criteria andFld14GreaterThan(String value) {
            addCriterion("FLD14 >", value, "fld14");
            return (Criteria) this;
        }

        public Criteria andFld14GreaterThanOrEqualTo(String value) {
            addCriterion("FLD14 >=", value, "fld14");
            return (Criteria) this;
        }

        public Criteria andFld14LessThan(String value) {
            addCriterion("FLD14 <", value, "fld14");
            return (Criteria) this;
        }

        public Criteria andFld14LessThanOrEqualTo(String value) {
            addCriterion("FLD14 <=", value, "fld14");
            return (Criteria) this;
        }

        public Criteria andFld14Like(String value) {
            addCriterion("FLD14 like", value, "fld14");
            return (Criteria) this;
        }

        public Criteria andFld14NotLike(String value) {
            addCriterion("FLD14 not like", value, "fld14");
            return (Criteria) this;
        }

        public Criteria andFld14In(List<String> values) {
            addCriterion("FLD14 in", values, "fld14");
            return (Criteria) this;
        }

        public Criteria andFld14NotIn(List<String> values) {
            addCriterion("FLD14 not in", values, "fld14");
            return (Criteria) this;
        }

        public Criteria andFld14Between(String value1, String value2) {
            addCriterion("FLD14 between", value1, value2, "fld14");
            return (Criteria) this;
        }

        public Criteria andFld14NotBetween(String value1, String value2) {
            addCriterion("FLD14 not between", value1, value2, "fld14");
            return (Criteria) this;
        }

        public Criteria andFld15IsNull() {
            addCriterion("FLD15 is null");
            return (Criteria) this;
        }

        public Criteria andFld15IsNotNull() {
            addCriterion("FLD15 is not null");
            return (Criteria) this;
        }

        public Criteria andFld15EqualTo(String value) {
            addCriterion("FLD15 =", value, "fld15");
            return (Criteria) this;
        }

        public Criteria andFld15NotEqualTo(String value) {
            addCriterion("FLD15 <>", value, "fld15");
            return (Criteria) this;
        }

        public Criteria andFld15GreaterThan(String value) {
            addCriterion("FLD15 >", value, "fld15");
            return (Criteria) this;
        }

        public Criteria andFld15GreaterThanOrEqualTo(String value) {
            addCriterion("FLD15 >=", value, "fld15");
            return (Criteria) this;
        }

        public Criteria andFld15LessThan(String value) {
            addCriterion("FLD15 <", value, "fld15");
            return (Criteria) this;
        }

        public Criteria andFld15LessThanOrEqualTo(String value) {
            addCriterion("FLD15 <=", value, "fld15");
            return (Criteria) this;
        }

        public Criteria andFld15Like(String value) {
            addCriterion("FLD15 like", value, "fld15");
            return (Criteria) this;
        }

        public Criteria andFld15NotLike(String value) {
            addCriterion("FLD15 not like", value, "fld15");
            return (Criteria) this;
        }

        public Criteria andFld15In(List<String> values) {
            addCriterion("FLD15 in", values, "fld15");
            return (Criteria) this;
        }

        public Criteria andFld15NotIn(List<String> values) {
            addCriterion("FLD15 not in", values, "fld15");
            return (Criteria) this;
        }

        public Criteria andFld15Between(String value1, String value2) {
            addCriterion("FLD15 between", value1, value2, "fld15");
            return (Criteria) this;
        }

        public Criteria andFld15NotBetween(String value1, String value2) {
            addCriterion("FLD15 not between", value1, value2, "fld15");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CLS_UD_RPTDATA
     *
     * @mbggenerated do_not_delete_during_merge Fri Apr 11 17:46:05 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CLS_UD_RPTDATA
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}