package pams.repository.model;

public class ClsUdRptdata {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLS_UD_RPTDATA.GUID
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLS_UD_RPTDATA.RPTDATE
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    private String rptdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLS_UD_RPTDATA.RPTNO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    private String rptno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLS_UD_RPTDATA.BRANCHNAME
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    private String branchname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLS_UD_RPTDATA.BRANCHID
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    private String branchid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLS_UD_RPTDATA.CUSTNAME
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    private String custname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLS_UD_RPTDATA.CUSTNO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    private String custno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLS_UD_RPTDATA.CUSTPHONE1
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    private String custphone1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLS_UD_RPTDATA.AUM
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    private String aum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLS_UD_RPTDATA.BAL
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    private String bal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLS_UD_RPTDATA.FLD01
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    private String fld01;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLS_UD_RPTDATA.FLD02
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    private String fld02;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLS_UD_RPTDATA.FLD03
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    private String fld03;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLS_UD_RPTDATA.FLD04
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    private String fld04;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLS_UD_RPTDATA.FLD05
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    private String fld05;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLS_UD_RPTDATA.FLD06
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    private String fld06;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLS_UD_RPTDATA.FLD07
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    private String fld07;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLS_UD_RPTDATA.FLD08
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    private String fld08;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLS_UD_RPTDATA.FLD09
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    private String fld09;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLS_UD_RPTDATA.FLD10
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    private String fld10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLS_UD_RPTDATA.FLD11
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    private String fld11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLS_UD_RPTDATA.FLD12
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    private String fld12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLS_UD_RPTDATA.FLD13
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    private String fld13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLS_UD_RPTDATA.FLD14
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    private String fld14;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLS_UD_RPTDATA.FLD15
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    private String fld15;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLS_UD_RPTDATA.GUID
     *
     * @return the value of CLS_UD_RPTDATA.GUID
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLS_UD_RPTDATA.GUID
     *
     * @param guid the value for CLS_UD_RPTDATA.GUID
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLS_UD_RPTDATA.RPTDATE
     *
     * @return the value of CLS_UD_RPTDATA.RPTDATE
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public String getRptdate() {
        return rptdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLS_UD_RPTDATA.RPTDATE
     *
     * @param rptdate the value for CLS_UD_RPTDATA.RPTDATE
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public void setRptdate(String rptdate) {
        this.rptdate = rptdate == null ? null : rptdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLS_UD_RPTDATA.RPTNO
     *
     * @return the value of CLS_UD_RPTDATA.RPTNO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public String getRptno() {
        return rptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLS_UD_RPTDATA.RPTNO
     *
     * @param rptno the value for CLS_UD_RPTDATA.RPTNO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public void setRptno(String rptno) {
        this.rptno = rptno == null ? null : rptno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLS_UD_RPTDATA.BRANCHNAME
     *
     * @return the value of CLS_UD_RPTDATA.BRANCHNAME
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public String getBranchname() {
        return branchname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLS_UD_RPTDATA.BRANCHNAME
     *
     * @param branchname the value for CLS_UD_RPTDATA.BRANCHNAME
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public void setBranchname(String branchname) {
        this.branchname = branchname == null ? null : branchname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLS_UD_RPTDATA.BRANCHID
     *
     * @return the value of CLS_UD_RPTDATA.BRANCHID
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public String getBranchid() {
        return branchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLS_UD_RPTDATA.BRANCHID
     *
     * @param branchid the value for CLS_UD_RPTDATA.BRANCHID
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public void setBranchid(String branchid) {
        this.branchid = branchid == null ? null : branchid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLS_UD_RPTDATA.CUSTNAME
     *
     * @return the value of CLS_UD_RPTDATA.CUSTNAME
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public String getCustname() {
        return custname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLS_UD_RPTDATA.CUSTNAME
     *
     * @param custname the value for CLS_UD_RPTDATA.CUSTNAME
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public void setCustname(String custname) {
        this.custname = custname == null ? null : custname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLS_UD_RPTDATA.CUSTNO
     *
     * @return the value of CLS_UD_RPTDATA.CUSTNO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public String getCustno() {
        return custno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLS_UD_RPTDATA.CUSTNO
     *
     * @param custno the value for CLS_UD_RPTDATA.CUSTNO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public void setCustno(String custno) {
        this.custno = custno == null ? null : custno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLS_UD_RPTDATA.CUSTPHONE1
     *
     * @return the value of CLS_UD_RPTDATA.CUSTPHONE1
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public String getCustphone1() {
        return custphone1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLS_UD_RPTDATA.CUSTPHONE1
     *
     * @param custphone1 the value for CLS_UD_RPTDATA.CUSTPHONE1
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public void setCustphone1(String custphone1) {
        this.custphone1 = custphone1 == null ? null : custphone1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLS_UD_RPTDATA.AUM
     *
     * @return the value of CLS_UD_RPTDATA.AUM
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public String getAum() {
        return aum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLS_UD_RPTDATA.AUM
     *
     * @param aum the value for CLS_UD_RPTDATA.AUM
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public void setAum(String aum) {
        this.aum = aum == null ? null : aum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLS_UD_RPTDATA.BAL
     *
     * @return the value of CLS_UD_RPTDATA.BAL
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public String getBal() {
        return bal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLS_UD_RPTDATA.BAL
     *
     * @param bal the value for CLS_UD_RPTDATA.BAL
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public void setBal(String bal) {
        this.bal = bal == null ? null : bal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLS_UD_RPTDATA.FLD01
     *
     * @return the value of CLS_UD_RPTDATA.FLD01
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public String getFld01() {
        return fld01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLS_UD_RPTDATA.FLD01
     *
     * @param fld01 the value for CLS_UD_RPTDATA.FLD01
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public void setFld01(String fld01) {
        this.fld01 = fld01 == null ? null : fld01.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLS_UD_RPTDATA.FLD02
     *
     * @return the value of CLS_UD_RPTDATA.FLD02
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public String getFld02() {
        return fld02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLS_UD_RPTDATA.FLD02
     *
     * @param fld02 the value for CLS_UD_RPTDATA.FLD02
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public void setFld02(String fld02) {
        this.fld02 = fld02 == null ? null : fld02.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLS_UD_RPTDATA.FLD03
     *
     * @return the value of CLS_UD_RPTDATA.FLD03
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public String getFld03() {
        return fld03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLS_UD_RPTDATA.FLD03
     *
     * @param fld03 the value for CLS_UD_RPTDATA.FLD03
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public void setFld03(String fld03) {
        this.fld03 = fld03 == null ? null : fld03.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLS_UD_RPTDATA.FLD04
     *
     * @return the value of CLS_UD_RPTDATA.FLD04
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public String getFld04() {
        return fld04;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLS_UD_RPTDATA.FLD04
     *
     * @param fld04 the value for CLS_UD_RPTDATA.FLD04
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public void setFld04(String fld04) {
        this.fld04 = fld04 == null ? null : fld04.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLS_UD_RPTDATA.FLD05
     *
     * @return the value of CLS_UD_RPTDATA.FLD05
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public String getFld05() {
        return fld05;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLS_UD_RPTDATA.FLD05
     *
     * @param fld05 the value for CLS_UD_RPTDATA.FLD05
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public void setFld05(String fld05) {
        this.fld05 = fld05 == null ? null : fld05.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLS_UD_RPTDATA.FLD06
     *
     * @return the value of CLS_UD_RPTDATA.FLD06
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public String getFld06() {
        return fld06;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLS_UD_RPTDATA.FLD06
     *
     * @param fld06 the value for CLS_UD_RPTDATA.FLD06
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public void setFld06(String fld06) {
        this.fld06 = fld06 == null ? null : fld06.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLS_UD_RPTDATA.FLD07
     *
     * @return the value of CLS_UD_RPTDATA.FLD07
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public String getFld07() {
        return fld07;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLS_UD_RPTDATA.FLD07
     *
     * @param fld07 the value for CLS_UD_RPTDATA.FLD07
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public void setFld07(String fld07) {
        this.fld07 = fld07 == null ? null : fld07.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLS_UD_RPTDATA.FLD08
     *
     * @return the value of CLS_UD_RPTDATA.FLD08
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public String getFld08() {
        return fld08;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLS_UD_RPTDATA.FLD08
     *
     * @param fld08 the value for CLS_UD_RPTDATA.FLD08
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public void setFld08(String fld08) {
        this.fld08 = fld08 == null ? null : fld08.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLS_UD_RPTDATA.FLD09
     *
     * @return the value of CLS_UD_RPTDATA.FLD09
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public String getFld09() {
        return fld09;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLS_UD_RPTDATA.FLD09
     *
     * @param fld09 the value for CLS_UD_RPTDATA.FLD09
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public void setFld09(String fld09) {
        this.fld09 = fld09 == null ? null : fld09.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLS_UD_RPTDATA.FLD10
     *
     * @return the value of CLS_UD_RPTDATA.FLD10
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public String getFld10() {
        return fld10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLS_UD_RPTDATA.FLD10
     *
     * @param fld10 the value for CLS_UD_RPTDATA.FLD10
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public void setFld10(String fld10) {
        this.fld10 = fld10 == null ? null : fld10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLS_UD_RPTDATA.FLD11
     *
     * @return the value of CLS_UD_RPTDATA.FLD11
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public String getFld11() {
        return fld11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLS_UD_RPTDATA.FLD11
     *
     * @param fld11 the value for CLS_UD_RPTDATA.FLD11
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public void setFld11(String fld11) {
        this.fld11 = fld11 == null ? null : fld11.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLS_UD_RPTDATA.FLD12
     *
     * @return the value of CLS_UD_RPTDATA.FLD12
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public String getFld12() {
        return fld12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLS_UD_RPTDATA.FLD12
     *
     * @param fld12 the value for CLS_UD_RPTDATA.FLD12
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public void setFld12(String fld12) {
        this.fld12 = fld12 == null ? null : fld12.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLS_UD_RPTDATA.FLD13
     *
     * @return the value of CLS_UD_RPTDATA.FLD13
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public String getFld13() {
        return fld13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLS_UD_RPTDATA.FLD13
     *
     * @param fld13 the value for CLS_UD_RPTDATA.FLD13
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public void setFld13(String fld13) {
        this.fld13 = fld13 == null ? null : fld13.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLS_UD_RPTDATA.FLD14
     *
     * @return the value of CLS_UD_RPTDATA.FLD14
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public String getFld14() {
        return fld14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLS_UD_RPTDATA.FLD14
     *
     * @param fld14 the value for CLS_UD_RPTDATA.FLD14
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public void setFld14(String fld14) {
        this.fld14 = fld14 == null ? null : fld14.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLS_UD_RPTDATA.FLD15
     *
     * @return the value of CLS_UD_RPTDATA.FLD15
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public String getFld15() {
        return fld15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLS_UD_RPTDATA.FLD15
     *
     * @param fld15 the value for CLS_UD_RPTDATA.FLD15
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public void setFld15(String fld15) {
        this.fld15 = fld15 == null ? null : fld15.trim();
    }
}