package pams.repository.model;

import java.math.BigDecimal;
import java.util.Date;

public class SvClsCustinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SV_CLS_CUSTINFO.GUID
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SV_CLS_CUSTINFO.BRANCH_NAME
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    private String branchName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SV_CLS_CUSTINFO.BRANCH_ID
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    private String branchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SV_CLS_CUSTINFO.CUST_NAME
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    private String custName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SV_CLS_CUSTINFO.CERT_TYPE
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    private String certType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SV_CLS_CUSTINFO.CERT_NO
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    private String certNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SV_CLS_CUSTINFO.CONTACT_INFO1
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    private String contactInfo1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SV_CLS_CUSTINFO.CONTACT_INFO2
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    private String contactInfo2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SV_CLS_CUSTINFO.AUM_MONTH_CURR
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    private BigDecimal aumMonthCurr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SV_CLS_CUSTINFO.AUM_MONTH_LAST
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    private BigDecimal aumMonthLast;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SV_CLS_CUSTINFO.AUM_TIMEPOINT_DEP
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    private BigDecimal aumTimepointDep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SV_CLS_CUSTINFO.LOAN_BAL
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    private BigDecimal loanBal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SV_CLS_CUSTINFO.OPENACT_BRANCH_ID
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    private String openactBranchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SV_CLS_CUSTINFO.OPENACT_BRANCH_NAME
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    private String openactBranchName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SV_CLS_CUSTINFO.CTS_MARGIN_BAL
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    private BigDecimal ctsMarginBal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SV_CLS_CUSTINFO.RPT_DATE
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    private String rptDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SV_CLS_CUSTINFO.RPT_TYPE
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    private String rptType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SV_CLS_CUSTINFO.OPER_ID
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    private String operId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SV_CLS_CUSTINFO.OPER_DATE
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    private Date operDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SV_CLS_CUSTINFO.IMP_DATE
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    private Date impDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SV_CLS_CUSTINFO.DELETE_FLAG
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    private String deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SV_CLS_CUSTINFO.GUID
     *
     * @return the value of SV_CLS_CUSTINFO.GUID
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SV_CLS_CUSTINFO.GUID
     *
     * @param guid the value for SV_CLS_CUSTINFO.GUID
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SV_CLS_CUSTINFO.BRANCH_NAME
     *
     * @return the value of SV_CLS_CUSTINFO.BRANCH_NAME
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    public String getBranchName() {
        return branchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SV_CLS_CUSTINFO.BRANCH_NAME
     *
     * @param branchName the value for SV_CLS_CUSTINFO.BRANCH_NAME
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    public void setBranchName(String branchName) {
        this.branchName = branchName == null ? null : branchName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SV_CLS_CUSTINFO.BRANCH_ID
     *
     * @return the value of SV_CLS_CUSTINFO.BRANCH_ID
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    public String getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SV_CLS_CUSTINFO.BRANCH_ID
     *
     * @param branchId the value for SV_CLS_CUSTINFO.BRANCH_ID
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    public void setBranchId(String branchId) {
        this.branchId = branchId == null ? null : branchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SV_CLS_CUSTINFO.CUST_NAME
     *
     * @return the value of SV_CLS_CUSTINFO.CUST_NAME
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    public String getCustName() {
        return custName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SV_CLS_CUSTINFO.CUST_NAME
     *
     * @param custName the value for SV_CLS_CUSTINFO.CUST_NAME
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    public void setCustName(String custName) {
        this.custName = custName == null ? null : custName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SV_CLS_CUSTINFO.CERT_TYPE
     *
     * @return the value of SV_CLS_CUSTINFO.CERT_TYPE
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    public String getCertType() {
        return certType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SV_CLS_CUSTINFO.CERT_TYPE
     *
     * @param certType the value for SV_CLS_CUSTINFO.CERT_TYPE
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    public void setCertType(String certType) {
        this.certType = certType == null ? null : certType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SV_CLS_CUSTINFO.CERT_NO
     *
     * @return the value of SV_CLS_CUSTINFO.CERT_NO
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    public String getCertNo() {
        return certNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SV_CLS_CUSTINFO.CERT_NO
     *
     * @param certNo the value for SV_CLS_CUSTINFO.CERT_NO
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    public void setCertNo(String certNo) {
        this.certNo = certNo == null ? null : certNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SV_CLS_CUSTINFO.CONTACT_INFO1
     *
     * @return the value of SV_CLS_CUSTINFO.CONTACT_INFO1
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    public String getContactInfo1() {
        return contactInfo1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SV_CLS_CUSTINFO.CONTACT_INFO1
     *
     * @param contactInfo1 the value for SV_CLS_CUSTINFO.CONTACT_INFO1
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    public void setContactInfo1(String contactInfo1) {
        this.contactInfo1 = contactInfo1 == null ? null : contactInfo1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SV_CLS_CUSTINFO.CONTACT_INFO2
     *
     * @return the value of SV_CLS_CUSTINFO.CONTACT_INFO2
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    public String getContactInfo2() {
        return contactInfo2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SV_CLS_CUSTINFO.CONTACT_INFO2
     *
     * @param contactInfo2 the value for SV_CLS_CUSTINFO.CONTACT_INFO2
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    public void setContactInfo2(String contactInfo2) {
        this.contactInfo2 = contactInfo2 == null ? null : contactInfo2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SV_CLS_CUSTINFO.AUM_MONTH_CURR
     *
     * @return the value of SV_CLS_CUSTINFO.AUM_MONTH_CURR
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    public BigDecimal getAumMonthCurr() {
        return aumMonthCurr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SV_CLS_CUSTINFO.AUM_MONTH_CURR
     *
     * @param aumMonthCurr the value for SV_CLS_CUSTINFO.AUM_MONTH_CURR
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    public void setAumMonthCurr(BigDecimal aumMonthCurr) {
        this.aumMonthCurr = aumMonthCurr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SV_CLS_CUSTINFO.AUM_MONTH_LAST
     *
     * @return the value of SV_CLS_CUSTINFO.AUM_MONTH_LAST
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    public BigDecimal getAumMonthLast() {
        return aumMonthLast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SV_CLS_CUSTINFO.AUM_MONTH_LAST
     *
     * @param aumMonthLast the value for SV_CLS_CUSTINFO.AUM_MONTH_LAST
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    public void setAumMonthLast(BigDecimal aumMonthLast) {
        this.aumMonthLast = aumMonthLast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SV_CLS_CUSTINFO.AUM_TIMEPOINT_DEP
     *
     * @return the value of SV_CLS_CUSTINFO.AUM_TIMEPOINT_DEP
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    public BigDecimal getAumTimepointDep() {
        return aumTimepointDep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SV_CLS_CUSTINFO.AUM_TIMEPOINT_DEP
     *
     * @param aumTimepointDep the value for SV_CLS_CUSTINFO.AUM_TIMEPOINT_DEP
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    public void setAumTimepointDep(BigDecimal aumTimepointDep) {
        this.aumTimepointDep = aumTimepointDep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SV_CLS_CUSTINFO.LOAN_BAL
     *
     * @return the value of SV_CLS_CUSTINFO.LOAN_BAL
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    public BigDecimal getLoanBal() {
        return loanBal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SV_CLS_CUSTINFO.LOAN_BAL
     *
     * @param loanBal the value for SV_CLS_CUSTINFO.LOAN_BAL
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    public void setLoanBal(BigDecimal loanBal) {
        this.loanBal = loanBal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SV_CLS_CUSTINFO.OPENACT_BRANCH_ID
     *
     * @return the value of SV_CLS_CUSTINFO.OPENACT_BRANCH_ID
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    public String getOpenactBranchId() {
        return openactBranchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SV_CLS_CUSTINFO.OPENACT_BRANCH_ID
     *
     * @param openactBranchId the value for SV_CLS_CUSTINFO.OPENACT_BRANCH_ID
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    public void setOpenactBranchId(String openactBranchId) {
        this.openactBranchId = openactBranchId == null ? null : openactBranchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SV_CLS_CUSTINFO.OPENACT_BRANCH_NAME
     *
     * @return the value of SV_CLS_CUSTINFO.OPENACT_BRANCH_NAME
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    public String getOpenactBranchName() {
        return openactBranchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SV_CLS_CUSTINFO.OPENACT_BRANCH_NAME
     *
     * @param openactBranchName the value for SV_CLS_CUSTINFO.OPENACT_BRANCH_NAME
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    public void setOpenactBranchName(String openactBranchName) {
        this.openactBranchName = openactBranchName == null ? null : openactBranchName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SV_CLS_CUSTINFO.CTS_MARGIN_BAL
     *
     * @return the value of SV_CLS_CUSTINFO.CTS_MARGIN_BAL
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    public BigDecimal getCtsMarginBal() {
        return ctsMarginBal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SV_CLS_CUSTINFO.CTS_MARGIN_BAL
     *
     * @param ctsMarginBal the value for SV_CLS_CUSTINFO.CTS_MARGIN_BAL
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    public void setCtsMarginBal(BigDecimal ctsMarginBal) {
        this.ctsMarginBal = ctsMarginBal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SV_CLS_CUSTINFO.RPT_DATE
     *
     * @return the value of SV_CLS_CUSTINFO.RPT_DATE
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    public String getRptDate() {
        return rptDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SV_CLS_CUSTINFO.RPT_DATE
     *
     * @param rptDate the value for SV_CLS_CUSTINFO.RPT_DATE
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    public void setRptDate(String rptDate) {
        this.rptDate = rptDate == null ? null : rptDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SV_CLS_CUSTINFO.RPT_TYPE
     *
     * @return the value of SV_CLS_CUSTINFO.RPT_TYPE
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    public String getRptType() {
        return rptType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SV_CLS_CUSTINFO.RPT_TYPE
     *
     * @param rptType the value for SV_CLS_CUSTINFO.RPT_TYPE
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    public void setRptType(String rptType) {
        this.rptType = rptType == null ? null : rptType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SV_CLS_CUSTINFO.OPER_ID
     *
     * @return the value of SV_CLS_CUSTINFO.OPER_ID
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    public String getOperId() {
        return operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SV_CLS_CUSTINFO.OPER_ID
     *
     * @param operId the value for SV_CLS_CUSTINFO.OPER_ID
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    public void setOperId(String operId) {
        this.operId = operId == null ? null : operId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SV_CLS_CUSTINFO.OPER_DATE
     *
     * @return the value of SV_CLS_CUSTINFO.OPER_DATE
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    public Date getOperDate() {
        return operDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SV_CLS_CUSTINFO.OPER_DATE
     *
     * @param operDate the value for SV_CLS_CUSTINFO.OPER_DATE
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    public void setOperDate(Date operDate) {
        this.operDate = operDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SV_CLS_CUSTINFO.IMP_DATE
     *
     * @return the value of SV_CLS_CUSTINFO.IMP_DATE
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    public Date getImpDate() {
        return impDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SV_CLS_CUSTINFO.IMP_DATE
     *
     * @param impDate the value for SV_CLS_CUSTINFO.IMP_DATE
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    public void setImpDate(Date impDate) {
        this.impDate = impDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SV_CLS_CUSTINFO.DELETE_FLAG
     *
     * @return the value of SV_CLS_CUSTINFO.DELETE_FLAG
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SV_CLS_CUSTINFO.DELETE_FLAG
     *
     * @param deleteFlag the value for SV_CLS_CUSTINFO.DELETE_FLAG
     *
     * @mbggenerated Tue Dec 18 13:28:46 CST 2012
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }
}